<?php

namespace Database\Factories;

use App\Models\PurchaseOrder;
use App\Models\PurchaseOrderItem;
use App\Models\Stock;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\PurchaseOrder>
 */
class PurchaseOrderFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            // The name is automatically generated by the model's creating event.
            // We just need to define the other attributes.
            'date' => $this->faker->date(),
            'status' => $this->faker->randomElement(['pending', 'checked', 'requested', 'completed']),
        ];
    }

    /**
     * Configure the model factory.
     *
     * @return $this
     */
    public function configure(): static
    {
        return $this->afterCreating(function (PurchaseOrder $purchaseOrder) {
            // Get 30 random stock items to choose from.
            $stocks = Stock::inRandomOrder()->limit(30)->get();

            // Create a random number of purchase order items (between 1 and 5)
            // for the newly created purchase order.
            $numberOfItems = $this->faker->numberBetween(1, 5);

            for ($i = 0; $i < $numberOfItems; $i++) {
                // Ensure we don't try to use a stock item that doesn't exist.
                if ($stocks->count() > 0) {
                    $stock = $this->faker->randomElement($stocks);

                    // Check if the item has already been added to this purchase order.
                    $existingItem = $purchaseOrder->purchaseOrderItems()->where('stock_id', $stock->id)->first();

                    // If the item doesn't exist, create it.
                    if (!$existingItem) {
                        PurchaseOrderItem::factory()->create([
                            'purchase_order_id' => $purchaseOrder->id,
                            'stock_id' => $stock->id,
                            'quantity' => $this->faker->numberBetween(1, 100),
                            'is_approved' => $this->faker->boolean(50),
                        ]);
                    }
                }
            }
        });
    }
}
